package fxLaturi.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import fxLaturi.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.18 09:35:30 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LaturiMainTest {
}