package laturi.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import laturi.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.03.20 19:09:49 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AjoneuvoTest {



  // Generated by ComTest BEGIN
  /** testParse69 */
  @Test
  public void testParse69() {    // Ajoneuvo: 69
    Ajoneuvo ajoneuvo = new Ajoneuvo(); 
    ajoneuvo.parse("   2  |  VAU-456   | Seat |  Mii"); 
    assertEquals("From: Ajoneuvo line: 72", 2, ajoneuvo.getTunnusNro()); 
    ajoneuvo.rekisteroi(); 
    int n = ajoneuvo.getTunnusNro(); 
    ajoneuvo.parse(""+(n+20));  // Otetaan merkkijonosta vain tunnusnumero
    ajoneuvo.rekisteroi();  // ja tarkistetaan että seuraavalla kertaa tulee yhtä isompi
    assertEquals("From: Ajoneuvo line: 79", n+20+1, ajoneuvo.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi120 */
  @Test
  public void testRekisteroi120() {    // Ajoneuvo: 120
    Ajoneuvo auto1 = new Ajoneuvo(); 
    assertEquals("From: Ajoneuvo line: 122", 0, auto1.getTunnusNro()); 
    auto1.rekisteroi(); 
    Ajoneuvo auto2 = new Ajoneuvo(); 
    auto2.rekisteroi(); 
    int n1 = auto1.getTunnusNro(); 
    int n2 = auto2.getTunnusNro(); 
    assertEquals("From: Ajoneuvo line: 128", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString164 */
  @Test
  public void testToString164() {    // Ajoneuvo: 164
    Ajoneuvo ajoneuvo = new Ajoneuvo(); 
    ajoneuvo.parse("   2  |  VAU-456   |Seat |   Mii"); 
    assertEquals("From: Ajoneuvo line: 167", true, ajoneuvo.toString().startsWith("2|VAU-456|Seat|"));  // on enemmäkin kuin 3 kenttää, siksi loppu |
  } // Generated by ComTest END
}