package laturi.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import laturi.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.02.22 12:50:31 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AjoneuvoTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi71 */
  @Test
  public void testRekisteroi71() {    // Ajoneuvo: 71
    Ajoneuvo auto1 = new Ajoneuvo(); 
    assertEquals("From: Ajoneuvo line: 73", 0, auto1.getTunnusNro()); 
    auto1.rekisteroi(); 
    Ajoneuvo auto2 = new Ajoneuvo(); 
    auto2.rekisteroi(); 
    int n1 = auto1.getTunnusNro(); 
    int n2 = auto2.getTunnusNro(); 
    assertEquals("From: Ajoneuvo line: 79", n2-1, n1); 
  } // Generated by ComTest END
}