package laturi.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import laturi.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.02.19 22:27:23 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AjoneuvotTest {


  // Generated by ComTest BEGIN
  /** 
   * testLisaa37 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa37() throws SailoException {    // Ajoneuvot: 37
    Ajoneuvot ajoneuvot = new Ajoneuvot(); 
    Ajoneuvo auto1 = new Ajoneuvo(), auto2 = new Ajoneuvo(); 
    assertEquals("From: Ajoneuvot line: 41", 0, ajoneuvot.getLkm()); 
    ajoneuvot.lisaa(auto1); assertEquals("From: Ajoneuvot line: 42", 1, ajoneuvot.getLkm()); 
    ajoneuvot.lisaa(auto2); assertEquals("From: Ajoneuvot line: 43", 2, ajoneuvot.getLkm()); 
    ajoneuvot.lisaa(auto1); assertEquals("From: Ajoneuvot line: 44", 3, ajoneuvot.getLkm()); 
    assertEquals("From: Ajoneuvot line: 45", auto1, ajoneuvot.anna(0)); 
    assertEquals("From: Ajoneuvot line: 46", auto2, ajoneuvot.anna(1)); 
    assertEquals("From: Ajoneuvot line: 47", auto1, ajoneuvot.anna(2)); 
    assertEquals("From: Ajoneuvot line: 48", false, ajoneuvot.anna(1) == auto1); 
    assertEquals("From: Ajoneuvot line: 49", true, ajoneuvot.anna(1) == auto2); 
    try {
    assertEquals("From: Ajoneuvot line: 50", auto1, ajoneuvot.anna(3)); 
    fail("Ajoneuvot: 50 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    ajoneuvot.lisaa(auto1); assertEquals("From: Ajoneuvot line: 51", 4, ajoneuvot.getLkm()); 
    ajoneuvot.lisaa(auto1); assertEquals("From: Ajoneuvot line: 52", 5, ajoneuvot.getLkm()); 
    try {
    ajoneuvot.lisaa(auto1); 
    fail("Ajoneuvot: 53 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}