package laturi.test;
// Generated by ComTest BEGIN
import laturi.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.03.02 15:15:34 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LatauksetTest {


  // Generated by ComTest BEGIN
  /** testIterator82 */
  @Test
  public void testIterator82() {    // Lataukset: 82
    Lataukset latausKerrat = new Lataukset(); 
    Lataus auto21 = new Lataus(2); latausKerrat.lisaa(auto21); 
    Lataus auto11 = new Lataus(1); latausKerrat.lisaa(auto11); 
    Lataus auto22 = new Lataus(2); latausKerrat.lisaa(auto22); 
    Lataus auto12 = new Lataus(1); latausKerrat.lisaa(auto12); 
    Lataus auto23 = new Lataus(2); latausKerrat.lisaa(auto23); 
    Iterator<Lataus> i2=latausKerrat.iterator(); 
    assertEquals("From: Lataukset line: 94", auto21, i2.next()); 
    assertEquals("From: Lataukset line: 95", auto11, i2.next()); 
    assertEquals("From: Lataukset line: 96", auto22, i2.next()); 
    assertEquals("From: Lataukset line: 97", auto12, i2.next()); 
    assertEquals("From: Lataukset line: 98", auto23, i2.next()); 
    try {
    assertEquals("From: Lataukset line: 99", auto12, i2.next()); 
    fail("Lataukset: 99 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
    int n = 0; 
    int anrot[] = { 2,1,2,1,2} ; 
    for ( Lataus lat:latausKerrat ) {
    assertEquals("From: Lataukset line: 105", anrot[n], lat.getAjoneuvoNro()); n++; 
    }
    assertEquals("From: Lataukset line: 108", 5, n); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaLataukset123 */
  @Test
  public void testAnnaLataukset123() {    // Lataukset: 123
    Lataukset latausKerrat = new Lataukset(); 
    Lataus kerta21 = new Lataus(2); latausKerrat.lisaa(kerta21); 
    Lataus kerta11 = new Lataus(1); latausKerrat.lisaa(kerta11); 
    Lataus kerta22 = new Lataus(2); latausKerrat.lisaa(kerta22); 
    Lataus kerta12 = new Lataus(1); latausKerrat.lisaa(kerta12); 
    Lataus kerta23 = new Lataus(2); latausKerrat.lisaa(kerta23); 
    Lataus kerta51 = new Lataus(5); latausKerrat.lisaa(kerta51); 
    List<Lataus> loytyneet; 
    loytyneet = latausKerrat.annaLataukset(3); 
    assertEquals("From: Lataukset line: 136", 0, loytyneet.size()); 
    loytyneet = latausKerrat.annaLataukset(1); 
    assertEquals("From: Lataukset line: 138", 2, loytyneet.size()); 
    assertEquals("From: Lataukset line: 139", true, loytyneet.get(0) == kerta11); 
    assertEquals("From: Lataukset line: 140", true, loytyneet.get(1) == kerta12); 
    loytyneet = latausKerrat.annaLataukset(5); 
    assertEquals("From: Lataukset line: 142", 1, loytyneet.size()); 
    assertEquals("From: Lataukset line: 143", true, loytyneet.get(0) == kerta51); 
  } // Generated by ComTest END
}