package laturi.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import laturi.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.03.02 15:16:32 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LaturiTest {


  // Generated by ComTest BEGIN
  /** 
   * testLisaa32 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa32() throws SailoException {    // Laturi: 32
    Laturi laturi = new Laturi(); 
    Ajoneuvo auto1 = new Ajoneuvo(), auto2 = new Ajoneuvo(); 
    auto1.rekisteroi(); auto2.rekisteroi(); 
    assertEquals("From: Laturi line: 37", 0, laturi.getAjoneuvoja()); 
    laturi.lisaa(auto1); assertEquals("From: Laturi line: 38", 1, laturi.getAjoneuvoja()); 
    laturi.lisaa(auto2); assertEquals("From: Laturi line: 39", 2, laturi.getAjoneuvoja()); 
    laturi.lisaa(auto1); assertEquals("From: Laturi line: 40", 3, laturi.getAjoneuvoja()); 
    assertEquals("From: Laturi line: 41", 3, laturi.getAjoneuvoja()); 
    assertEquals("From: Laturi line: 42", auto1, laturi.annaAjoneuvo(0)); 
    assertEquals("From: Laturi line: 43", auto2, laturi.annaAjoneuvo(1)); 
    assertEquals("From: Laturi line: 44", auto1, laturi.annaAjoneuvo(2)); 
    try {
    assertEquals("From: Laturi line: 45", auto1, laturi.annaAjoneuvo(3)); 
    fail("Laturi: 45 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    laturi.lisaa(auto1); assertEquals("From: Laturi line: 46", 4, laturi.getAjoneuvoja()); 
    laturi.lisaa(auto1); assertEquals("From: Laturi line: 47", 5, laturi.getAjoneuvoja()); 
    try {
    laturi.lisaa(auto1); 
    fail("Laturi: 48 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaLataukset94 */
  @Test
  public void testAnnaLataukset94() {    // Laturi: 94
    Laturi laturi = new Laturi(); 
    Ajoneuvo auto1 = new Ajoneuvo(), auto2 = new Ajoneuvo(), auto3 = new Ajoneuvo(); 
    auto1.rekisteroi(); auto2.rekisteroi(); auto3.rekisteroi(); 
    int id1 = auto1.getTunnusNro(); 
    int id2 = auto2.getTunnusNro(); 
    Lataus kerta11 = new Lataus(id1); laturi.lisaa(kerta11); 
    Lataus kerta12 = new Lataus(id1); laturi.lisaa(kerta12); 
    Lataus kerta21 = new Lataus(id2); laturi.lisaa(kerta21); 
    Lataus kerta22 = new Lataus(id2); laturi.lisaa(kerta22); 
    Lataus kerta23 = new Lataus(id2); laturi.lisaa(kerta23); 
    List<Lataus> loytyneet; 
    loytyneet = laturi.annaLataukset(auto3); 
    assertEquals("From: Laturi line: 110", 0, loytyneet.size()); 
    loytyneet = laturi.annaLataukset(auto1); 
    assertEquals("From: Laturi line: 112", 2, loytyneet.size()); 
    assertEquals("From: Laturi line: 113", true, loytyneet.get(0) == kerta11); 
    assertEquals("From: Laturi line: 114", true, loytyneet.get(1) == kerta12); 
    loytyneet = laturi.annaLataukset(auto2); 
    assertEquals("From: Laturi line: 116", 3, loytyneet.size()); 
    assertEquals("From: Laturi line: 117", true, loytyneet.get(0) == kerta21); 
  } // Generated by ComTest END
}